export const commonErrors: Record<string, string> = {
  UNAUTHORIZED: "No tienes permiso para realizar esta acción",
  FORBIDDEN: "Acceso denegado",
  UNKNOWN_ERROR: "Ocurrió un error inesperado",
  JOB_AREA_KEY_EXISTS: "Ya existe un área de trabajo con esta clave",
  JOB_AREA_NOT_FOUND: "El área de trabajo no fue encontrada",
  INVALID_AREA_ID: "El ID del área no es válido",
  INVALID_SALARY_RANGE: "El rango de salario no es válido",
  JOB_NOT_FOUND: "La vacante no fue encontrada o no existe",
  APPLICATION_EXISTS: "Ya existe una aplicación para esta vacante",
  APPLICATION_NOT_FOUND: "La aplicación no fue encontrada o no existe",
  CANDIDATE_NOT_FOUND: "El candidato no fue encontrado",
  INVALID_FILE: "El archivo no es válido",
  INVALID_JOB_ID: "El ID de la vacante no es válido",
  MISSING_EMAIL: "El correo electrónico es requerido",
  EMPTY_FILE: "El archivo está vacío",
  FILE_TOO_LARGE: "El archivo excede el tamaño máximo permitido",
  UNSUPPORTED_FILE_TYPE: "Tipo de archivo no soportado",
  DOCUMENT_PROCESSING_ERROR: "Error al procesar el documento",
  AI_SERVICE_ERROR: "Error en el servicio de IA",
  DATABASE_ERROR: "Error en la base de datos",
  INTERNAL_SERVER_ERROR: "Ocurrió un error inesperado",
  VALIDATION_ERROR: "Error de validación, verifique los datos ingresados",
  JOB_AREA_HAS_JOBS:
    "El área de trabajo no puede ser eliminada porque tiene vacantes asociadas",
};
